
development:
  adapter: postgresql
  encoding: utf8
  database: zach_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: zach_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: zach_production
  pool: 5
  username:
  password: